apiVersion: v1
kind: Service
metadata:
  name: micro-auth
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-auth
  ports:
  - name: micro-auth
    port: 8002
    targetPort: 8002
    protocol: TCP
